### ISSUE TITLE
[BUG]: Drive depth repeated call throws exception

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/ephys-link#168]
### Describe the bug

Repeated calls to `drive_to_depth` triggered by using keyboard control

```bash
Task exception was never retrieved
future: <Task finished name='Task-40511' coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\Kenneth\Documents\ephys-link\venv\Lib\site-packages\socketio\asyncio_server.py:522> exception=AttributeError("'Event' object has no attribute 'position'")>
Traceback (most recent call last):
  File "C:\Users\Kenneth\Documents\ephys-link\venv\Lib\site-packages\socketio\asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kenneth\Documents\ephys-link\venv\Lib\site-packages\socketio\asyncio_server.py", line 558, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kenneth\Documents\ephys-link\ephys_link\server.py", line 295, in drive_to_depth
    return await platform.drive_to_depth(manipulator_id, depth, speed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kenneth\Documents\ephys-link\ephys_link\platform_handler.py", line 217, in drive_to_depth
    return await self._drive_to_depth(manipulator_id, depth, speed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kenneth\Documents\ephys-link\ephys_link\platforms\sensapex_handler.py", line 59, in _drive_to_depth
    return await self.manipulators[manipulator_id].drive_to_depth(depth, speed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kenneth\Documents\ephys-link\ephys_link\platforms\sensapex_manipulator.py", line 133, in drive_to_depth
    target_pos = deepcopy(self._move_queue[0].position)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Event' object has no attribute 'position'
```

### To Reproduce

Use keyboard control on Pinpoint and hold `z` or `x`

### Expected behavior

No exceptions

### Do you plan to solve this issue yourself?

Yes

**Comment by kjy5** [comment]
Repeated calls should not be supported
