### ISSUE TITLE
Invalid method encountered when no system connected

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/ephys-link#84]
**Describe the bug**
Non-crashing error called when no system is connected for an extended period of time (is repeatedly called)

```
Error handling request
Traceback (most recent call last):
  File "C:\Users\Kenneth\Documents\ephys-link\lib\site-packages\aiohttp\web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

**To Reproduce**

1. Start server
2. Connect, then disconnect Pinpoint
3. Wait a very long time

**Expected behavior**

**Screenshots**

<img width="874" alt="image" src="https://user-images.githubusercontent.com/82800265/189751671-b24dbb2f-761a-4974-bf4a-b1241898d167.png">

**Comment by kjy5** [comment]
Appears to be random pings from other systems
